package user;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 05 23:24:37 EDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int KSTRING = 31;
  public static final int EQUALS = 14;
  public static final int INT = 21;
  public static final int MINUS = 13;
  public static final int STATIC = 30;
  public static final int AND = 19;
  public static final int LT = 11;
  public static final int RPAR = 10;
  public static final int BOOL = 34;
  public static final int COMMA = 16;
  public static final int SEMICOL = 17;
  public static final int CLASS = 28;
  public static final int PLUS = 12;
  public static final int MAIN = 25;
  public static final int IF = 20;
  public static final int THIS = 23;
  public static final int DOT = 15;
  public static final int EXCL = 18;
  public static final int EOF = 0;
  public static final int RETURN = 33;
  public static final int TRUE = 37;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int NUMBER = 4;
  public static final int VOID = 26;
  public static final int LBRACK = 7;
  public static final int TIMES = 2;
  public static final int LBRACE = 5;
  public static final int ELSE = 24;
  public static final int RBRACK = 8;
  public static final int WHILE = 27;
  public static final int PUBLIC = 32;
  public static final int RBRACE = 6;
  public static final int EXTENDS = 35;
  public static final int LPAR = 9;
  public static final int LEN = 29;
  public static final int FALSE = 38;
  public static final int PRINT = 36;
  public static final int IDENTIFIER = 3;
}

